# Generated by Django 5.0.7 on 2024-07-12 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_myclubuser_venue_alter_event_manager_event_attendees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='web_address',
            new_name='web',
        ),
    ]
